name: Java CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java files
      run: |
        mkdir -p out
        javac -d out src/variables_Datatypes/*.java

    - name: Run Java program
      run: |
        java -cp out variables_Datatypes.PersonalDetails

    - name: Archive build outputs
      uses: actions/upload-artifact@v3
      with:
        name: java-build
        path: out/